#!/usr/bin/env node
/**
 * sync-pancake.mjs — bring a Pancake 2 topping into this site.
 *
 *   npm run pancake:sync                       topping "julia" from the published web-pancake
 *   npm run pancake:sync -- neon               another topping
 *   npm run pancake:sync -- julia --local ../../web-pancake   from a local checkout
 *
 * Writes src/styles/pancake/theme.css (the topping's tokens) and components.css
 * (Pancake 2's component styles), each with a header saying where it came from.
 * Never edit those two files by hand: change the topping in web-pancake
 * (themes/<name>/map.json → import-theme.mjs), then sync again.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';

const args = process.argv.slice(2);
const topping = args.find((a) => !a.startsWith('--') && args[args.indexOf(a) - 1] !== '--local') ?? 'julia';
const localIndex = args.indexOf('--local');
const local = localIndex >= 0 ? resolve(args[localIndex + 1]) : null;
const REMOTE = 'https://juliasakakibara.github.io/web-pancake';
const OUT = join(process.cwd(), 'src', 'styles', 'pancake');

const files = [
  { from: `themes/${topping}/theme.css`, to: 'theme.css' },
  { from: 'components/components.css', to: 'components.css' },
];

async function read(path) {
  if (local) return readFileSync(join(local, path), 'utf8');
  const res = await fetch(`${REMOTE}/${path}?fresh=${Date.now()}`);
  if (!res.ok) throw new Error(`Could not load ${REMOTE}/${path} (HTTP ${res.status})`);
  return res.text();
}

mkdirSync(OUT, { recursive: true });
for (const f of files) {
  const css = await read(f.from);
  const header = `/* GENERATED by scripts/sync-pancake.mjs — do not edit.\n   Source: ${local ? 'local ' + local : REMOTE}/${f.from}\n   Topping: ${topping} · synced ${new Date().toISOString().slice(0, 10)}\n   Pancake 2 is built on letbe-ds (MIT) by m1ha1l0. */\n\n`;
  writeFileSync(join(OUT, f.to), header + css);
  console.log(`✓ ${f.to}  ← ${f.from} (${Math.round(css.length / 1024)} KB)`);
}
